### ISSUE TITLE
[Feature Request] Type ahead / Jump to file / Type to seek

### ISSUE THREAD

**Issue by NatoBoram** [pop-os/cosmic-files#490]
**Cosmic-files version:**

```yaml
cosmic-files:
  Installed: 0.1.0~1726864500~22.04~333d4e5
  Candidate: 0.1.0~1726864500~22.04~333d4e5
  Version table:
 *** 0.1.0~1726864500~22.04~333d4e5 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug description:**

When opening COSMIC Files, I would like to be able to quickly select a folder by typing the first few letters in its name then quickly open it by pressing <kbd>Enter</kbd>.

**Steps to reproduce:**

1. Open COSMIC Files
2. Press <kbd>D</kbd>

**Expected behavior:**

The folder `Desktop` should be highlighted

**Other notes:**

* https://gitlab.gnome.org/GNOME/nautilus/-/issues/1157
* https://github.com/lubomir-brindza/nautilus-typeahead

Example in Nautilus:

![image](https://github.com/user-attachments/assets/9979a20f-fb39-41dc-9ac4-357ca9163793)
